language: python
virtualenv:
  system_site_packages: true
env:
  global:
    - LENSFUN_GIT="git://git.code.sf.net/p/lensfun/code"
  matrix:
    - USE_LATEST_LENSFUN=true
    - USE_LATEST_LENSFUN=false
install:
  - sudo apt-get install python-numpy
  # see http://stackoverflow.com/a/5244583/60982 on how to extract latest SVN tag 
  - if [ $USE_LATEST_LENSFUN == true ]; then
      cd .. ;
      git clone $LENSFUN_GIT lensfun ;
      cd lensfun ;
      git checkout `git describe --abbrev=0 --tags` # latest version
      ./configure ;
      sudo make install ;
      echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/99local.conf ;
      sudo ldconfig ;
      cd ../lensfunpy ;
    else
      sudo apt-get install liblensfun0 liblensfun-dev ;
    fi
  - pip install cython
  - pip install .
script: nosetests