language: python
virtualenv:
  system_site_packages: true
env:
  global:
    - LENSFUN_SVN="svn://svn.berlios.de/lensfun"
  matrix:
    - USE_LATEST_LENSFUN=true
    - USE_LATEST_LENSFUN=false
install:
  - sudo apt-get install python-numpy
  # see http://stackoverflow.com/a/5244583/60982 on how to extract latest SVN tag 
  - if [ "${USE_LATEST_LENSFUN}" == true ]; then
      cd .. ;
      svn co $LENSFUN_SVN`svn log -v $LENSFUN_SVN/tags | awk '/^   A/ { print $2 }' | head -1` lensfun ;
      cd lensfun ;
      ./configure ;
      sudo make install ;
      cd ../lensfunpy ;
    else
      sudo apt-get install liblensfun0 liblensfun-dev ;
    fi
  - pip install cython
  - pip install .
script: nosetests