language: python

virtualenv:
  system_site_packages: true

env:
  global:
    - LENSFUN_GIT="git://git.code.sf.net/p/lensfun/code"
    # GitHub Access Token to trigger lensfunpy-mac-wheels builds
    - secure: "l7N3ME70ltwbnQSdcTV9QiE+QtCMrnbNJthHAGpvqsGVXPS7TNrF92UhuI67e1ALeWqF+JK5lr9wml0OPn1dDnZt8aZ1R3OKQm+3eQVx1bg6csqYCu1OY9AJ+0ZRVOd0PsqZ5RU+JSrYJUPOTiDj7uZD74MFMAhcW2iAGaKm+iM="   
  matrix:
    - USE_LATEST_LENSFUN=true
    - USE_LATEST_LENSFUN=false

install:
  - sudo apt-get install python-numpy
  - if [ $USE_LATEST_LENSFUN == true ]; then
      cd .. ;
      git clone $LENSFUN_GIT lensfun ;
      cd lensfun ;
      git checkout `git describe --abbrev=0 --tags` ;
      cmake . ;
      sudo make install ;
      echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/99local.conf ;
      sudo ldconfig ;
      cd ../lensfunpy ;
    else
      sudo apt-get install liblensfun0 liblensfun-dev ;
    fi
  - pip install cython

script: python setup.py nosetests --verbosity=3

after_success:
  # change to 'pip install travispy' once 0.3 released 
  - if [ $USE_LATEST_LIBRAW == true ]; then
      pip install https://github.com/menegazzo/travispy/archive/master.zip ;
      python -c "import os; from travispy import TravisPy; t = TravisPy.github_auth(os.environ['GITHUB_TOKEN']); t.build(t.branch('mac-wheels', 'neothemachine/lensfunpy-mac-wheels').id).restart()" ;
    fi

deploy:
  provider: pypi
  user: neothemachine
  password:
    secure: "pCn0C1WsU6HoslSXhVZySIzn0f2mfiCWHC7t4tbkhLCrBQuSNNIgSf1lvQdsEAbluqi8IFTmRasfi9cOV/PDO+4W1O8qpPhYVc2INfF4lFs6ef/Ow3kK5+exnjaUMbc0SyAjekQ8f0z0rVKvDANvByAYeeeQbj8pCXBHV9SSs98="
  on:
    tags: true
    all_branches: true
    condition: $USE_LATEST_LENSFUN = false