language: python
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get install python-numpy
  - $LENSFUN_INSTALL
  - pip install cython
  - pip install .
script: nosetests
env:
  global:
    - LENSFUN_SVN="svn://svn.berlios.de/lensfun"
  matrix:
    - LENSFUN_INSTALL="sudo apt-get install liblensfun0 liblensfun-dev"
    - LENSFUN_INSTALL="cd .. ; svn co $LENSFUN_SVN`svn log -v $LENSFUN_SVN/tags | awk '/^   A/ { print $2 }' | head -1` lensfun ; cd lensfun ; ./configure ; sudo make install ; cd ../lensfunpy"