language: python

virtualenv:
  system_site_packages: true

env:
  global:
    - LENSFUN_GIT="git://git.code.sf.net/p/lensfun/code"
    # GitHub Access Token to trigger lensfunpy-mac-wheels builds
    - secure: "l7N3ME70ltwbnQSdcTV9QiE+QtCMrnbNJthHAGpvqsGVXPS7TNrF92UhuI67e1ALeWqF+JK5lr9wml0OPn1dDnZt8aZ1R3OKQm+3eQVx1bg6csqYCu1OY9AJ+0ZRVOd0PsqZ5RU+JSrYJUPOTiDj7uZD74MFMAhcW2iAGaKm+iM="   
  matrix:
    - USE_LATEST_LENSFUN=true
    - USE_LATEST_LENSFUN=false

git:
  submodules: false

install:
  - if [ $USE_LATEST_LENSFUN == true ]; then
      cd .. ;
      git clone $LENSFUN_GIT lensfun ;
      cd lensfun ;
      git checkout `git describe --abbrev=0 --tags` ;
      cmake . ;
      sudo make install ;
      echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/99local.conf ;
      sudo ldconfig ;
      cd ../lensfunpy ;
    else
      sudo apt-get install liblensfun-dev ;
    fi
  - pip install -r dev-requirements.txt
  - python setup.py sdist
  - pip install dist/*.tar.gz

script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../test
  - cd ..

after_success:
  - if [ $USE_LATEST_LENSFUN == true ]; then
      pip install travispy ;
      python -c "import os; from travispy import TravisPy; t = TravisPy.github_auth(os.environ['GITHUB_TOKEN']); t.build(t.branch('mac-wheels', 'neothemachine/lensfunpy').id).restart()" ;
    fi

deploy:
  provider: pypi
  user: neothemachine
  password:
    secure: "pCn0C1WsU6HoslSXhVZySIzn0f2mfiCWHC7t4tbkhLCrBQuSNNIgSf1lvQdsEAbluqi8IFTmRasfi9cOV/PDO+4W1O8qpPhYVc2INfF4lFs6ef/Ow3kK5+exnjaUMbc0SyAjekQ8f0z0rVKvDANvByAYeeeQbj8pCXBHV9SSs98="
  on:
    tags: true
    all_branches: true
    condition: $USE_LATEST_LENSFUN = false