language: python

virtualenv:
  system_site_packages: true

env:
  global:
    - LENSFUN_GIT="git://git.code.sf.net/p/lensfun/code"
    # GitHub Access Token to trigger lensfunpy-mac-wheels builds
    - secure: "W/oAfrVmQrtm7dO7mNbKSnFsywRdEvZdbYFksU6WmM39BgIiEeoiGoNE5oB51XvYJOps1rSHA04arjR5I2JK636M/X6GDRI76yrQ6KafsajCbciP8DZKOGs5MEf1FR8O1YfTJXc0f/4+qRXTZ7yVUbJaEeKDfXKT/fVzpfbRhhw="   
  matrix:
    - USE_LATEST_LENSFUN=false
    - USE_LATEST_LENSFUN=true

git:
  submodules: false

install:
  # checkout master, see https://sourceforge.net/p/lensfun/bugs/36/
  # git checkout -f `git describe --abbrev=0 --tags` ;
  - if [ $USE_LATEST_LENSFUN == true ]; then
      cd .. ;
      git clone $LENSFUN_GIT lensfun ;
      cd lensfun ;
      git checkout 75a845abf ;
      cmake . -DBUILD_TESTS=off ;
      sudo make install ;
      echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/99local.conf ;
      sudo ldconfig ;
      cd ../lensfunpy ;
    else
      sudo apt-get install liblensfun-dev ;
    fi
  - travis_retry pip install -r dev-requirements.txt
  - python setup.py sdist
  - pip install dist/*.tar.gz

script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../test
  - cd ..

after_success:
  - if [ $USE_LATEST_LENSFUN == true ]; then
      pip install travispy ;
      travis_retry python -c "import os; from travispy import TravisPy; t = TravisPy.github_auth(os.environ['GITHUB_TOKEN']); t.build(t.branch('mac-wheels', 'neothemachine/lensfunpy').id).restart()" ;
    fi

before_deploy:
  # otherwise sphinx would fail
  - python setup.py build_ext --inplace

deploy:
  provider: pypi
  user: neothemachine
  password:
    secure: "pCn0C1WsU6HoslSXhVZySIzn0f2mfiCWHC7t4tbkhLCrBQuSNNIgSf1lvQdsEAbluqi8IFTmRasfi9cOV/PDO+4W1O8qpPhYVc2INfF4lFs6ef/Ow3kK5+exnjaUMbc0SyAjekQ8f0z0rVKvDANvByAYeeeQbj8pCXBHV9SSs98="
  on:
    tags: true
    all_branches: true
    condition: $USE_LATEST_LENSFUN = false